#
#
# Copyright (C) 2012, Sergey Shcherbakov <shchers@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

# Project sources
C_SRC := \
	source/main.c \
	source/board_common.c \
	source/board_configuration.c

CFLAGS := -I include

CFLAGS += -DUSE_FULL_ASSERT

 # Common sources, targets and scripts
include common.mk
